# If .Values.kerberoshub.forwarder.enabled is set to true 
{{- if .Values.kerberoshub.forwarder.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-forwarder
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-forwarder
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vault-forwarder
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: vault-forwarder
          image: "{{ .Values.global.imageRegistry }}{{ .Values.kerberoshub.forwarder.repository }}:{{ .Values.kerberoshub.forwarder.tag }}"
          imagePullPolicy: {{ .Values.kerberoshub.forwarder.pullPolicy }}
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
          env:
            - name: ITERATION_SPEED
              value: "5"
            - name: BUFFER_TIME
              value: "3"
            # Mongodb
            - name: MONGODB_URI
              value: "{{ .Values.mongodb.uri }}"
            - name: MONGODB_DATABASE_CLOUD
              value: "Kerberos"
            - name: MONGODB_HOST
              value: "{{ .Values.mongodb.host }}"
            - name: MONGODB_AUTHENTICATION_MECHANISM
              value: "{{ .Values.mongodb.authenticationMechanism }}"
            - name: MONGODB_DATABASE_CREDENTIALS
              value: "{{ .Values.mongodb.adminDatabase }}"
            - name: MONGODB_USERNAME
              value: "{{ .Values.mongodb.username }}"
            - name: MONGODB_PASSWORD
              value: "{{ .Values.mongodb.password }}"

            # Mqtt (VERNEMQ)
            - name: MQTT_URI
              value: "{{ .Values.mqtt.host }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.mqtt.username }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.mqtt.password }}"
{{- end }}
