apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: admin-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: admin
