name: Deploy on Kind

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: [v0.21.0, v0.22.0, v0.23.0, v0.24.0]
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: ${{ matrix.kind }}
      - name: Print Kubernetes Version
        run: |
          kubectl version
      - name: Test Kubernetes Cluster
        run: |
          kubectl get no
          kubectl get pods -A -o wide
          kubectl get sc
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Kerberos Hub helm chart
        id: install-kerberos-hub
        run: |
          kubectl create namespace kerberos-hub
          helm install hub ./charts/hub --values charts/hub/values.yaml -n kerberos-hub --create-namespace
          echo "Sleeping for 300 seconds, give time for the helm chart to create the pods" && sleep 300
          kubectl get pods -A -o wide
          kubectl get pods -A -o wide | grep hub-frontend | awk '{print $3}' | grep -q '1/1' && echo "hub-frontend pod is running with status 1/1" || (echo "kerberos-hub pod is not running with status 1/1" && exit 1)
