apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hub-metrics-servicemonitor
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    service: pipe
    release: prometheus
spec:
  selector:
    matchLabels:
      service: pipe
  endpoints:
    - port: hub-metrics
      interval: 15s
      path: /metrics
